name: ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
      
      # - name: Install staticcheck
      #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Formatting and Linting
        run: test -z $(go fmt ./...) && staticcheck ./...

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      - name: Run GoSec
        run: gosec ./... 

      - name: Run Tests
        run: go test -cover ./...